# Quaynt — Multi-stage Dockerfile
# Requires Docker Compose v2.20+ for depends_on conditions and profiles

# ---------------------------------------------------------------------------
# Stage 1: deps — install production + dev node_modules
# ---------------------------------------------------------------------------
FROM node:24-slim AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

# ---------------------------------------------------------------------------
# Stage 2: builder — build Next.js standalone + esbuild worker bundle
# ---------------------------------------------------------------------------
FROM node:24-slim AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build
RUN npm run build:worker

# ---------------------------------------------------------------------------
# Stage 3: runner — production image
# ---------------------------------------------------------------------------
FROM node:24-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

RUN addgroup --system --gid 1001 nodejs && \
    adduser --system --uid 1001 --ingroup nodejs nextjs

# Next.js standalone output
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Worker bundle
COPY --from=builder --chown=nextjs:nodejs /app/dist/worker.cjs ./dist/worker.cjs

# package.json for version reference (health endpoint)
COPY --from=builder --chown=nextjs:nodejs /app/package.json ./package.json

# Worker runtime dependencies — pg-boss, pg, and their transitive deps.
# Next.js standalone tracing does not include these since worker.ts is not
# a Next.js entry point. This list was generated by tracing the dependency
# tree of pg-boss and pg.
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/pg-boss ./node_modules/pg-boss
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/pg ./node_modules/pg
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/pg-pool ./node_modules/pg-pool
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/pg-protocol ./node_modules/pg-protocol
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/pg-types ./node_modules/pg-types
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/pg-connection-string ./node_modules/pg-connection-string
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/pg-int8 ./node_modules/pg-int8
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/pgpass ./node_modules/pgpass
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/split2 ./node_modules/split2
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/postgres-array ./node_modules/postgres-array
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/postgres-bytea ./node_modules/postgres-bytea
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/postgres-date ./node_modules/postgres-date
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/postgres-interval ./node_modules/postgres-interval
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/cron-parser ./node_modules/cron-parser
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/luxon ./node_modules/luxon
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/serialize-error ./node_modules/serialize-error
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/non-error ./node_modules/non-error
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/type-fest ./node_modules/type-fest
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/tagged-tag ./node_modules/tagged-tag
COPY --from=deps --chown=nextjs:nodejs /app/node_modules/xtend ./node_modules/xtend

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]

# ---------------------------------------------------------------------------
# Stage 4: dev — development with hot reload (source via bind mounts)
# ---------------------------------------------------------------------------
FROM node:24-slim AS dev
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
EXPOSE 3000
CMD ["npm", "run", "dev"]
